-- Insert sample supplements products
INSERT INTO products (name, name_ar, description, description_ar, price, category, is_active, stock_quantity, suitable_for, suitable_for_ar, usage_instructions, usage_instructions_ar) VALUES
('Whey Protein Isolate', 'واي بروتين أيزوليت', 'High-quality whey protein isolate with 25g protein per serving. Fast absorption for post-workout recovery.', 'بروتين واي عالي الجودة يحتوي على 25 جرام بروتين لكل حصة. سريع الامتصاص للتعافي بعد التمرين.', 2500, 'supplements', true, 50, 'Athletes, fitness enthusiasts, those looking to build muscle', 'الرياضيين، عشاق اللياقة، الباحثين عن بناء العضلات', 'Mix 1 scoop (30g) with 200-300ml water or milk. Take post-workout or between meals.', 'امزج ملعقة واحدة (30 جم) مع 200-300 مل ماء أو حليب. تناوله بعد التمرين أو بين الوجبات.'),

('Omega-3 Fish Oil', 'أوميجا 3 زيت السمك', 'Premium fish oil capsules with EPA and DHA. Supports heart, brain and joint health.', 'كبسولات زيت السمك الممتازة مع EPA و DHA. تدعم صحة القلب والدماغ والمفاصل.', 450, 'supplements', true, 100, 'Adults seeking cardiovascular and cognitive support', 'البالغين الباحثين عن دعم القلب والأوعية الدموية والإدراك', 'Take 2 capsules daily with meals.', 'تناول كبسولتين يوميًا مع الوجبات.'),

('Multivitamin Complex', 'مجمع الفيتامينات المتعددة', 'Complete daily multivitamin with essential vitamins and minerals for overall health.', 'فيتامينات يومية كاملة مع الفيتامينات والمعادن الأساسية للصحة العامة.', 350, 'supplements', true, 150, 'Anyone looking to fill nutritional gaps in their diet', 'أي شخص يبحث عن سد الفجوات الغذائية في نظامه الغذائي', 'Take 1 tablet daily with breakfast.', 'تناول قرص واحد يوميًا مع الإفطار.'),

('BCAA Powder', 'بودرة الأحماض الأمينية BCAA', 'Branched-chain amino acids for muscle recovery and reduced fatigue during workouts.', 'أحماض أمينية متفرعة السلسلة لتعافي العضلات وتقليل التعب أثناء التمارين.', 800, 'supplements', true, 75, 'Athletes and those doing intense training', 'الرياضيين ومن يقومون بتدريبات مكثفة', 'Mix 1 scoop with 500ml water. Drink during or after workout.', 'امزج ملعقة واحدة مع 500 مل ماء. اشرب أثناء أو بعد التمرين.'),

('Creatine Monohydrate', 'كرياتين مونوهيدرات', 'Pure creatine monohydrate for increased strength, power and muscle gains.', 'كرياتين مونوهيدرات نقي لزيادة القوة والطاقة ومكاسب العضلات.', 600, 'supplements', true, 80, 'Those looking to enhance strength and athletic performance', 'الباحثين عن تعزيز القوة والأداء الرياضي', 'Take 5g daily with water or juice. Best taken post-workout.', 'تناول 5 جم يوميًا مع الماء أو العصير. يفضل تناوله بعد التمرين.');
