// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evfoljpyhcfwjgwljhyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Zm9sanB5aGNmd2pnd2xqaHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2MjA4NDEsImV4cCI6MjA4NDE5Njg0MX0.YPflfLSaKfyP6SUonURUkz9a8inHVYnGfOw4GNk6cBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});